Embeds:
  Welcome:
    Title: "Bienvenue"
    Description: "Bienvenue sur ArionRP, {user-mention}! \n\n Je te conseil de bien lire le <#1004681054671614024> & <#1004681058320662528> ! \n\n Invité par : {inviter-mention}\n Membres totals : {total}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  Leave:
    Title: "Bye bye"
    Description: "Aure-voir, {user-mention} vien de nous quitter bonne continuation 😁 ! \n\n Membres totals : {total}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  Shop:
    Title: "🛍️ Boutique du serveur (Page {current-page}/{max-pages})"
    Description: "Bienvenue dans la boutique du serveur ! Vous pouvez acheter des articles de la boutique en lançant la commande `-buy <item>`."
    Format: ["{item-display}", "{item-description}"]
  CoinTop:
    Title: "👑 Tableau des pièces de monnaie (Page {current-page}/{max-pages})"
    Footer: "Total des pièces collectées : {totalcoins}"
  LevelTop:
    Title: "✨ Level Leaderboard (Page {current-page}/{max-pages})"
    Footer: "Total XP Collected: {totalxp}"
  Ticket:
    Title: "🎟️ Ticket"
    Description: "Salut, {user-mention}. Merci d'avoir contacté notre équipe d'assistance. Nous serons prêts à vous aider des que possible. En attendant, veuillez décrire vos problèmes avec le plus de détails possible."
    Footer: "Ticket system by ARION"
    Timestamp: true
    Thumbnail: "{bot-pfp}"
    Fields:
      - Name: "Raison"
        Value: "{reason}"
  Announcement:
    Title: "📣 {title} 📣"
    Description: "{description}"
    Footer: "Annonce par : {user-tag}"
    Timestamp: true
    FooterIcon: "{user-pfp}"
    AuthorIcon: "{bot-pfp}"
  Update:
    Title: "📰 Mise à jour {update-version}"
    Description: "{update}"
    Timestamp: true
    Footer: "Par : {user-tag}"
    FooterIcon: "{user-pfp}"
  Poll:
    Title: "📊 Sondage | {question}"
    Description: "{description}"
    Timestamp: true
  Links:
    Title: "🔗 Liens"
    Description: "Tous les liens relatifs au serveur"
  SuggestionSent:
    Title: "📬 Suggestion envoyée"
    Description: "Merci pour la suggestion ! Si vous souhaitez la supprimer, réagissez à la page [suggestion]({link}) avec 🗑️"
    Timestamp: true
    Color: "#25de1f"
  PendingSuggestion:
    Title: "Suggestion #{id}"
    Fields:
      - Name: "Suggestion"
        Value: "{suggestion}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "De"
        Value: "{user-mention}"
        Inline: true
    Thumbnail: "{user-pfp}"
    Timestamp: true
  Suggestion:
    Title: "Suggestion #{id} | {status}"
    Fields:
      - Name: "Suggestion"
        Value: "{suggestion}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "De"
        Value: "{user-mention}"
        Inline: true
      - Name: "Raisons {status}"
        Value: "{reason}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "Votes"
        Value: "**Des votes positifs :** {upvotes-amount} ({upvotes-percentage})\n**Les votes négatifs :** {downvotes-amount} ({downvotes-percentage})\n**Total :** {opinions}"
        Inline: true
    Footer: "Changé en {status} par : {changed-by-tag}"
    Thumbnail: "{user-pfp}"
    Timestamp: true
  IP:
    Author: "IP du serveur"
    Description: "Voici l'ip du serveur **node.01.cloudheberge.fr:30086**. N'hésitez pas à vous joindre à nous !"
    AuthorIcon: "https://cdn.discordapp.com/attachments/1004681042873032715/1005449731843043358/Arion_2.1.png?size=4096"
  ApplicationCreated:
    Title: "Application"
    Description: "{user-mention}, merci d'avoir créé une demande. Remplissez ces questions et notre équipe examinera votre candidature dans les plus brefs délais."
  ApplicationPosition:
    Title: "Position"
    Description: "Pour quel poste souhaitez-vous postuler ? Les postes actuels sont {positions}"
  ApplicationComplete:
    Title: "Demande complète"
    Description: "Votre demande est complète. Un membre du personnel l'examinera et prendra une décision dans les meilleurs délais."
  BugReported:
    Title: "🐛 Bug rapporté"
    Description: "Merci de signaler le bug ! Nos développeurs vont se pencher sur le problème dès que possible."
    Timestamp: true
  PendingBugreport:
    Title: "Rapport de bug | En attente d'approbation"
    Fields:
      - Name: "Bug"
        Value: "{bug}"
        Inline: true
      - Name: "De"
        Value: "{user-mention}"
        Inline: true
    Thumbnail: "{user-pfp}"
    Timestamp: true
  Bugreport:
    Title: "Rapport de bug | {status}"
    Fields:
      - Name: "Bug"
        Value: "{bug}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - Name: "De"
        Value: "{user-mention}"
        Inline: true
      - Name: "Raison"
        Value: "{reason}"
        Inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
    Footer: "Changé en {status} par : {changed-by-tag}"
    Thumbnail: "{user-pfp}"
    Timestamp: true
  Ping:
    - Title: ":signal_strength: Bot ping"
      Fields:
        - name: "Latence de l'API"
          value: "{api-ping} ms"
      Timestamp: true
    - Title: ":signal_strength: Bot ping"
      Fields:
        - name: "Latence de l'API"
          value: "{api-ping} ms"
          inline: true
        - name: "Latence du robot"
          value: "{bot-ping} ms"
          inline: true
      Timestamp: true
  CategorizedHelp:
    Footer: "{bot-displayname}"
    FooterIcon: "{bot-pfp}"
    Timestamp: true
    Description: "Utilisez `/help command <nom de la commande>` pour rechercher une commande spécifique."
    Fields:
      - name: ":earth_americas: Général"
        value: "{prefix}help module general"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":tickets: Tickets"
        value: "{prefix}help module tickets"
        inline: true
      - name: ":coin: Coins"
        value: "{prefix}help module coins"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":sparkles: XP"
        value: "{prefix}help module xp"
        inline: true
      - name: ":pick: FiveM"
        value: "{prefix}help module minecraft"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":video_game: Fun"
        value: "{prefix}help module fun"
        inline: true
      - name: ":musical_note: Music"
        value: "{prefix}help module music"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":dividers: Other"
        value: "{prefix}help module other"
        inline: true
  CategorizedStaffHelp:
    Footer: "{bot-displayname}"
    FooterIcon: "{bot-pfp}"
    Timestamp: true
    Description: "Use `-shelp command <command name>` to search up a specific command"
    Fields:
      - name: ":cop: Moderation"
        value: "{prefix}staffhelp module moderation"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":tools: Admin"
        value: "{prefix}staffhelp module admin"
        inline: true
      - name: ":tada: Giveaways"
        value: "{prefix}staffhelp module giveaways"
        inline: true
      - name: "\u200b"
        value: "\u200b"
        inline: true
      - name: ":desktop: Management"
        value: "{prefix}staffhelp module management"
        inline: true
  LevelUp:
    Title: "⬆️ Level Up"
    Description: "{user-mention}, you just leveled up! You are now level **{level}**! {reward}"
  DMWelcome:
    Description: "Bienvenue dans French City RP !"
  Banned:
    Title: "Banned"
    Description: "You were banned from the **{server-name}** guild!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Banned By"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reason"
        Value: "{reason}"
  UserBanned:
    Title: ":anger: User Banned"
    Description: "{user-mention} ({user-id}) has been banned by {executor-mention} for `{reason}`"
    Color: "#f52c2c"
    Timestamp: true
  Kicked:
    Title: "Kicked"
    Description: "You were kicked from the **{server-name}** guild!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Kicked By"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reason"
        Value: "{reason}"
  UserKicked:
    Title: "👞 User Kicked"
    Description: "{user-mention} has been kicked by {executor-mention} for `{reason}`"
    Color: "#fc9803"
    Timestamp: true
  Muted:
    Title: "Muted"
    Description: "You were muted in the **{server-name}** guild!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Muted By"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reason"
        Value: "{reason}"
  UserMuted:
    Title: "🔇 User Muted"
    Description: "{user-mention} has been muted by {executor-mention} for `{reason}`"
    Color: "#1c1c1c"
    Timestamp: true
  Tempbanned:
    Title: "Temp Banned"
    Description: "You were temporarily banned from the **{server-name}** guild!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Banned By"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reason"
        Value: "{reason}"
      - Name: "End Date"
        Value: "<t:{timestamp}:f> (<t:{timestamp}:R>)"
  UserTempbanned:
    Title: ":anger: User Temporarily Banned"
    Description: "{user-mention} ({user-id}) has been temporarily banned by {executor-mention} for `{reason}` until <t:{timestamp}:f> (<t:{timestamp}:R>)"
    Color: "#f52c2c"
    Timestamp: true
  Tempmuted:
    Title: "Temp Muted"
    Description: "You were temporarily muted in the **{server-name}** guild!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Muted By"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Reason"
        Value: "{reason}"
      - Name: "End Date"
        Value: "<t:{timestamp}:f> (<t:{timestamp}:R>)"
  UserTempmuted:
    Title: "🔇 User Temporarily Muted"
    Description: "{user-mention} has been temporarily muted by {executor-mention} for `{reason}` until <t:{timestamp}:f> (<t:{timestamp}:R>)"
    Color: "#1c1c1c"
    Timestamp: true
  Blacklisted:
    Title: "Blacklisted"
    Description: "You were blacklisted from running a command in the **{server-name}** guild!"
    Timestamp: true
    Color: "#f52c2c"
    Fields:
      - Name: "Command"
        Value: "{command}"
      - Name: "Blacklisted By"
        Value: "{executor-mention} ({executor-tag})"
  UserBlacklisted:
    All:
      Title: "🛑 User Blacklisted"
      Description: "{user-mention} is now blacklisted from running **all** commands"
      Timestamp: true
      Color: "#f52c2c"
    Command:
      Title: "🛑 User Blacklisted"
      Description: "{user-mention} is now blacklisted from running the `{command}` command"
      Timestamp: true
      Color: "#f52c2c"
  UserUnbanned:
    Title: "☑️ User Unbanned"
    Description: "{user-mention} ({user-id}) has been unbanned by {executor-mention}"
    Timestamp: true
  Unblacklisted:
    Title: "Unblacklisted"
    Description: "You were unblacklisted from running a command in the **{server-name}** guild!"
    Timestamp: true
    Color: "#25de1f"
    Fields:
      - Name: "Command"
        Value: "{command}"
      - Name: "Unblacklisted By"
        Value: "{executor-mention} ({executor-tag})"
  Unmuted:
    Title: "Unmuted"
    Description: "You were unmuted in the **{server-name}** guild!"
    Timestamp: true
    Color: "#25de1f"
    Fields:
      - Name: "Unmuted By"
        Value: "{executor-mention} ({executor-tag})"
  UserUnmuted:
    Title: "🔊 User Unmuted"
    Description: "{user-mention} has been unmuted by {executor-mention}"
    Timestamp: true
  Warned:
    Title: "⚠️Uh oh! You've been warned!"
    Description: "You were warned in the **{server-name}** guild!"
    Timestamp: true
    Color: "#fc9803"
    Fields:
      - Name: "Reason"
        Value: "{reason}"
      - Name: "Warned By"
        Value: "{executor-mention} ({executor-tag})"
      - Name: "Warning ID"
        Value: "{warning-id}"
      - Name: "Warning Count"
        Value: "{warning-count}"
  UserWarned:
    Title: "⚠️ User Warned"
    Description: "{user-mention} has been warned by {executor-mention} for `{reason}`"
    Color: "#fc9803"
    Timestamp: true
  UserAutoPunished:
    Title: "❗ Too Many Warnings"
    Description: "{user-mention} has reached **{warning-count} warnings**, so they have been automatically {punishment} {extra}"
    TempPunishExtraInfo: "({length})"
  Giveaway:
    Title: ":gift: Giveaway"
    Description: "{description}"
    Fields:
      - Name: "Prize"
        Value: "{prize}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Winners"
        Value: "{winners}"
        Inline: true
      - Name: "Hosted By"
        Value: "{host}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Giveaway Ends"
        Value: "{time-left}"
        Inline: true
      - Name: "\u200b"
        Value: "**React with the :tada: emoji to join!**\n\n{extra-entries}"
        Inline: false
    Footer: "Ends"
    Timestamp: true
  GiveawayWithRequirements:
    Title: ":gift: Giveaway"
    Description: "{description}"
    Fields:
      - Name: "Prize"
        Value: "{prize}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Winners"
        Value: "{winners}"
        Inline: true
      - Name: "Hosted By"
        Value: "{host}"
        Inline: true
      - Name: "\u200b"
        Value: "\u200b"
        Inline: true
      - Name: "Giveaway Ends"
        Value: "{time-left}"
        Inline: true
      - Name: "Requirements"
        Value: |-
          {requirements-coins}{requirements-xp}{requirements-level}{requirements-server}{requirements-roles-cant-have}{requirements-roles-must-have}{requirements-messages}

          **React with the :tada: emoji to join!**

          {extra-entries}
        Inline: false
    Footer: "Ends"
    Timestamp: true
  GiveawayEnded:
    Title: ":gift: Giveaway Ended"
    Fields:
      - Name: "Prize⠀⠀⠀⠀⠀"
        Value: "{prize}\n{description}"
        Inline: true
      - Name: "Hosted By⠀⠀⠀⠀⠀"
        Value: "{host}"
        Inline: true
      - Name: "Winners"
        Value: "{winners}"
        Inline: true
      - Name: "\u200b"
        Value: ":tada: **Create a ticket to claim your prize!**"
        Inline: false
    Timestamp: true
    Footer: "Ended"
  Reminder:
    Title: "⏰ Remind"
    Description: "Hey {user-mention}, don't forget this!"
    Fields:
      - Name: "🗒️ Your Reminder:"
        Value: "{reminder}"
    Timestamp: true
  JoinVoiceChannel:
    Title: User Joined Channel
    Fields:
      - name: Channel
        value: "{channel-name} ({channel-id})"
      - name: User
        value: "{user-mention} ({user-id})"
      - name: User Tag
        value: "{user-tag}"
      - name: Time
        value: "{time}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  LeaveVoiceChannel:
    Title: User Left Channel
    Fields:
      - name: Channel
        value: "{channel-name} ({channel-id})"
      - name: User
        value: "{user-mention} ({user-id})"
      - name: User Tag
        value: "{user-tag}"
      - name: Time
        value: "{time}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  SwitchVoiceChannel:
    Title: User Switched Channel
    Fields:
      - name: Old Channel
        value: "{old-channel-name} ({old-channel-id})"
      - name: New Channel
        value: "{new-channel-name} ({new-channel-id})"
      - name: User
        value: "{user-mention} ({user-id})"
      - name: User Tag
        value: "{user-tag}"
      - name: Time
        value: "{time}"
    Timestamp: true
    Thumbnail: "{user-pfp}"
  TestEmbed:
    Title: "This is a test embed for the buttons.yml"
    Components:
      - [ "custombutton_test_button" ]
  Msgtop:
    Title: "📩 Messages Sent Leaderboard (Page {current-page}/{max-pages})"
    Footer: "Total Messages Sent: {total_messages}"
  VCtop:
    Title: "🔊 Voice Time Leaderboard (Page {current-page}/{max-pages})"
    Footer: "Total Time Spent in VC: {total_time}"
  Uptime:
    Title: "Bot Uptime"
    Description: "The bot has been online for **{uptime}**"
    Timestamp: true
    Footer: "Corebot"
    FooterIcon: "{bot-pfp}"
  TicketStats:
    Author: "{user-displayname}"
    AuthorIcon: "{user-pfp}"
    Title: "Ticket Stats"
    Fields:
      - Name: "All Time"
        Value: "> **Messages:** {all-msgs}\n> **Tickets:** {all-tickets}\n> **Closes:** {all-closes}"
      - Name: "Past 30 Days"
        Value: "> **Messages:** {month-msgs}\n> **Tickets:** {month-tickets}\n> **Closes:** {month-closes}"
      - Name: "Past 7 Days"
        Value: "> **Messages:** {week-msgs}\n> **Tickets:** {week-tickets}\n> **Closes:** {week-closes}"
      - Name: "Past 24 Hours"
        Value: "> **Messages:** {day-msgs}\n> **Tickets:** {day-tickets}\n> **Closes:** {day-closes}"
    Timestamp: true